---
# This is the main trunk plugin file for // Navigaite.
# It it used to configure

version: 0.1
required_trunk_version: '>= 1.6.8'
cli:
  version: 1.22.12

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.21.7
    - node@22.16.0
    - python@3.12.2
    - ruby@3.4.2

lint:
  definitions:
    - name: eslint
      commands:
        - name: lint
          run_when: [cli, monitor, ci] # do not run from lsp (maybe too slow)

  enabled:
    - actionlint@1.7.7
    - bandit@1.8.6
    - black@25.1.0
    - buf-lint@1.31.0!
    - buildifier@8.2.1
    - cfnlint@1.38.0
    - checkov@3.2.454
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - dotenv-linter@3.3.0
    - dustilock@1.2.0
    - eslint@9.31.0
    - git-diff-check
    - gitleaks@8.28.0
    - gofmt@1.20.4
    - golangci-lint@1.64.8
    - hadolint@2.12.1-beta
    - isort@6.0.1
    - markdownlint@0.45.0
    - markdown-link-check@3.13.7
    - mypy@1.17.0
    - nancy@1.0.48
    - osv-scanner@2.0.3
    - oxipng@9.1.5
    - pragma-once
    - prettier@3.6.2:
        packages:
          - prettier-plugin-tailwindcss@0.6.14
    - prisma@6.12.0
    - pylint@3.3.7
    - renovate@41.43.2
    - rubocop@1.39.0
    - ruff@0.12.5
    - rustfmt@1.68.2
    - semgrep@1.130.0
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - sort-package-json@3.4.0
    - sql-formatter@15.6.6
    - stylelint@16.22.0:
        packages:
          - stylelint-config-standard@38.0.0
          - stylelint-config-tailwindcss@1.0.0
          - stylelint-config-clean-order@7.0.0
    - svgo@4.0.0
    - taplo@0.9.3
    - terrascan@1.19.1
    - trivy@0.64.1
    - trufflehog@3.90.2
    - yamllint@1.37.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.checkov.yaml
        - configs/.cspell.json
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.npmcheckrc
        - configs/.prettierignore
        - configs/.prettierrc
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.json
        - configs/svgo.config.mjs
        - configs/.yamllint.yaml

  ignore:
    - linters: [trufflehog, osv-scanner]
      paths: [package-lock.json]

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
