---
# This is the main trunk plugin file for // Navigaite.
# It it used to configure

version: 0.1
required_trunk_version: '>= 1.6.8'
cli:
  version: 1.22.12

# Applicable linters and actions will run with these runtime versions
runtimes:
  enabled:
    - go@1.21.7
    - node@22.16.0
    - python@3.12.2
    - ruby@3.4.2

lint:
  definitions:
    - name: eslint
      commands:
        - name: lint
          run_when: [cli, monitor, ci] # do not run from lsp (maybe too slow)

  enabled:
    - actionlint@1.7.8
    - bandit@1.8.6
    - black@25.9.0
    - buf-lint@1.31.0!
    - buildifier@8.2.1
    - cfnlint@1.40.3
    - checkov@3.2.489
    - clang-format@17.0.1
    - clang-tidy@17.0.1
    - clippy@1.71.1
    - dotenv-linter@3.3.0
    - dustilock@1.2.0
    - eslint@9.38.0
    - git-diff-check
    - gitleaks@8.28.0
    - gofmt@1.20.4
    - golangci-lint@1.64.8
    - hadolint@2.14.0
    - isort@7.0.0
    - markdownlint@0.45.0
    - markdown-link-check@3.13.7
    - mypy@1.18.2
    - nancy@1.0.52
    - osv-scanner@2.2.4
    - oxipng@9.1.5
    - pragma-once
    - prettier@3.6.2:
        packages:
          - prettier-plugin-tailwindcss@0.7.1
    - prisma@6.18.0
    - pylint@4.0.2
    - renovate@41.165.4
    - rubocop@1.39.0
    - ruff@0.14.2
    - rustfmt@1.68.2
    - semgrep@1.141.1
    - shellcheck@0.11.0
    - shfmt@3.6.0
    - sort-package-json@3.4.0
    - sql-formatter@15.6.10
    - stylelint@16.25.0:
        packages:
          - stylelint-config-standard@39.0.1
          - stylelint-config-tailwindcss@1.0.0
          - stylelint-config-clean-order@7.0.0
    - svgo@4.0.0
    - taplo@0.10.0
    - terrascan@1.19.1
    - trivy@0.67.2
    - trufflehog@3.90.12
    - yamllint@1.37.1

  # Sourcing repos will have these configs available to applicable linters
  exported_configs:
    - configs:
        - configs/.checkov.yaml
        - configs/.cspell.json
        - configs/.flake8
        - configs/.hadolint.yaml
        - configs/.isort.cfg
        - configs/.markdownlint.yaml
        - configs/.npmcheckrc
        - configs/.prettierignore
        - configs/.prettierrc
        - configs/.pylintrc
        - configs/.remarkrc.yaml
        - configs/ruff.toml
        - configs/rustfmt.toml
        - configs/.shellcheckrc
        - configs/.sqlfluff
        - configs/.stylelintrc.json
        - configs/svgo.config.mjs
        - configs/.yamllint.yaml

  ignore:
    - linters: [trufflehog, osv-scanner]
      paths: [package-lock.json]

# By sourcing this plugin, repos will enable these actions
actions:
  enabled:
    - trunk-announce
    - trunk-cache-prune
    - trunk-upgrade-available
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
