---
extends: default

rules:
  truthy:
    allowed-values:
      - 'true'
      - 'false'
      - 'on'
      - 'off'
  comments:
    min-spaces-from-content: 1
  quoted-strings:
    required: only-when-needed
    extra-allowed: ['{|}']
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
