---
name: 📅 Upgrade Trunk

on:
  schedule:
    # Weekly on Monday and Friday at 8 AM UTC
    - cron: 0 8 * * 1,5
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  trunk_upgrade:
    name: ⬆️ Upgrade Trunk Tools
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: ⬆️ Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
        with:
          add-paths: plugin.yaml
          arguments: --apply-to=plugin.yaml -n
          github-token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          base: main
          prefix: 'ci(trunk-upgrade): '
          labels: automerge
