---
name: 🔧 Nightly Maintenance

on:
  schedule:
    - cron: 0 2 * * 1-5
  workflow_dispatch: {}
  workflow_call: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  maintenance:
    name: // Navigaite
    uses: navigaite/.github/.github/workflows/cron-cleanup-actions.yaml@main
    secrets: inherit
