name: Flama Final

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  final:
    uses: maxbec/flama-delivery-platform/.github/workflows/reusable-final.yml@330544867f40c1116222ef2769db9da8a8d627cd
    with:
      base-sha: ${{ github.event.pull_request.base.sha }}
      head-sha: ${{ github.event.pull_request.head.sha }}
      platform-sha: 330544867f40c1116222ef2769db9da8a8d627cd
