---
# This workflow deploy a new release to the main branch
name: 🚀 New Release

run-name: '${{ github.workflow }} by ${{ github.actor }}'

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@main
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}
          release-type: node
          skip-github-pull-request: true

  release-please-pr:
    runs-on: ubuntu-latest
    needs:
      - release-please-release
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - id: release-pr
        uses: googleapis/release-please-action@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
          release-type: node
          fork: true
          skip-github-release: true
