---
# This workflow deploy a new release to the main branch
name: 🚀 New Release

run-name: '${{ github.workflow }} by ${{ github.actor }}'

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  create-release:
    name: Create Release
    permissions:
      contents: write
      discussions: write
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.current_version }}
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update version
        id: update-version
        env:
          VERSION_INCREMENT: major
        run: |
          version=$(npm version --no-git-tag-version ${{ env.VERSION_INCREMENT }})
          echo "New version: $version"
          echo "NEW_VERSION=${version}" >> $GITHUB_OUTPUT

      - name: Set user
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git config --global user.name "navigaite-workflow-app[bot]"
          git config --global user.email "133966083+navigaite-workflow-app[bot]@users.noreply.github.com"

      - name: Create Release Branch
        run: |
          git checkout main

      - name: Commit Version Update and push changes
        id: version-update
        run: |
          git add package.json package-lock.json
          git commit -m "chore(release): Bump version to ${{ steps.update-version.outputs.NEW_VERSION }}"
          git push origin main

      - name: Get Current Version
        id: version
        run: echo "current_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          custom_tag: ${{ steps.version.outputs.current_version }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.github_release.outputs.changelog}}
          make_latest: true
