---
# This workflow deploy a new release to the main branch
name: 🚀 New Release

run-name: '${{ github.workflow }} by ${{ github.actor }}'

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  create-release:
    name: Create Release
    permissions:
      contents: write
      discussions: write
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.current_version }}
    steps:
      - name: Generate a github token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Current Version
        id: version
        run: echo "current_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          custom_tag: ${{ steps.version.outputs.current_version }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ./.github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body_path: ./.github/misc/release-notes.tmpl
          generate_release_notes: true
          make_latest: true
